name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: "Generating PDF from pandoc"
        uses: docker://nherbaut/pandoc-latex-ieee:latest
        with:
          args: "--citeproc -o build/paper.pdf --bibliography=bibliography.bib --pdf-engine=pdflatex --csl=templates/bibliography.csl -s -f markdown --template=templates/template.latex paper.md" 
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ github.event.inputs.version }}
          message: ${{ github.event.inputs.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/paper.pdf
          
