name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
         path: paper.md
                
