name: Makefile CI

on:
  push:
    branches: [ "draft" ]
  pull_request:
    branches: [ "draft" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: librsvg2-bin texlive-full build-essential
        version: 1.0
    - name: rehash latex
      run: texconfig rehash
    - name: Installing pandoc
      run: wget https://github.com/jgm/pandoc/releases/download/3.1.6.2/pandoc-3.1.6.2-1-amd64.deb && sudo dpkg -i pandoc-3.1.6.2-1-amd64.deb
    
    - name: build pdf
      run: pandoc --version && pandoc --help && ls $PWD && make
    - name: Create Tag
      uses: negz/create-tag@v1
      with:
        version: ${{ github.event.inputs.version }}
        message: ${{ github.event.inputs.message }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            build/paper.pdf
            build/paper.tex



