name: Makefile CI

on:
  push:
    branches: [ "draft" ]
  pull_request:
    branches: [ "draft" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: librsvg2-bin texlive-full build-essential
        version: 1.0
    - name: Installing pandoc
      run: wget https://github.com/jgm/pandoc/releases/download/3.1.6.2/pandoc-3.1.6.2-1-amd64.deb && sudo dpkg -i pandoc-3.1.6.2-1-amd64.deb
    
    - name: build pdf
      run: pandoc --version && pandoc --help && ls $PWD && make
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: paper-draft-${{ github.sha }}
        release_name: Draft ${{ github.sha }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./build/resources.zip
        asset_name: paper-draft-${{ github.sha }}.zip
        asset_content_type: application/zip



